### PR TITLE
Added get domain block info

### PR DESCRIPTION
**Pull request by enricruiz**
Fix for http://jira.abiquo.com/browse/ABICLOUDPREMIUM-7807 and http://jira.abiquo.com/browse/ABICLOUDPREMIUM-7201

Depends on https://github.com/abiquo/aim/pull/27 and https://github.com/abiquo/libvirt-plugin/pull/50

### CODE REVIEW

**Comment by nacx** [comment]
+1

**Comment by apuig** [comment]
dont understand the commit removing all the licenses

**Comment by enricruiz** [comment]
41e5d7cbb8beb13ded921052066d21f0

**Comment by apuig** [comment]
+1

**Pull request merged**
